#define TEXT_UPPER_VERTICAL_OFFSET_MULT 14
#define TEXT_LOWER_VERTICAL_OFFSET_MULT 4

#define DISPLAY_TFT_SPLASH_TITLE_X 65
#define DISPLAY_TFT_SPLASH_TITLE_Y 100

#define DISPLAY_TFT_SPLASH_SUBTITLE_X 35
#define DISPLAY_TFT_SPLASH_SUBTITLE_Y 150

#define DISPLAY_TFT_STATUS_X 10
#define DISPLAY_TFT_STATUS_Y 318
#define DISPLAY_TFT_STATUS_HEIGHT 25
#define DISPLAY_TFT_STATUS_WIDTH 100

#define DISPLAY_TFT_CACHE_STATUS_X 130
#define DISPLAY_TFT_CACHE_STATUS_Y 312
#define DISPLAY_TFT_CACHE_STATUS_HEIGHT 7
#define DISPLAY_TFT_CACHE_STATUS_WIDTH 80

#define DISPLAY_TFT_ALERT_X 10
#define DISPLAY_TFT_ALERT_Y 150
#define DISPLAY_TFT_ALERT_HEIGHT 40

#define DISPLAY_TFT_LS_ALERT_X 10
#define DISPLAY_TFT_LS_ALERT_Y 150
#define DISPLAY_TFT_LS_ALERT_HEIGHT 40

#define DISPLAY_TFT_MENU_X 25
#define DISPLAY_TFT_MENU_Y 80
#define DISPLAY_TFT_MENU_WIDTH 180
#define DISPLAY_TFT_MENU_HEIGHT 215
#define DISPLAY_TFT_MENU_LINE_HEIGHT 36
#define DISPLAY_TFT_MENU_MAX_ITEM_LENGTH 12
#define DISPLAY_TFT_MENU_INDENT 3 // pixels to indent menu items
#define DISPLAY_TFT_MENU_VERTICAL_ITEM_OFFSET 5
#define DISPLAY_TFT_MENU_VERTICAL_TEXT_OFFSET 3

#define DISPLAY_TFT_MENU_SCROLL_UP_X 220
#define DISPLAY_TFT_MENU_SCROLL_UP_Y 110
#define DISPLAY_TFT_MENU_SCROLL_DOWN_X 220
#define DISPLAY_TFT_MENU_SCROLL_DOWN_Y 275
#define DISPLAY_TFT_MENU_SCROLL_RADIUS 6
#define DISPLAY_TFT_MENU_SCROLL_TOUCH_RADIUS 20
#define DISPLAY_TFT_MAIN_IMAGE_X 35
#define DISPLAY_TFT_MAIN_IMAGE_Y 120
#define DISPLAY_TFT_MAIN_IMAGE_WIDTH 64
#define DISPLAY_TFT_MAIN_IMAGE_HEIGHT 48
#define DISPLAY_TFT_MAIN_IMAGE_SUBTITLE_X 55 // relative to bottom left corner of image
#define DISPLAY_TFT_MAIN_IMAGE_SUBTITLE_Y 130 // relative to bottom left corner of image

#define DISPLAY_TFT_ALT_IMAGE_X 35
#define DISPLAY_TFT_ALT_IMAGE_Y 120
#define DISPLAY_TFT_ALT_IMAGE_WIDTH 64
#define DISPLAY_TFT_ALT_IMAGE_HEIGHT 48
#define DISPLAY_TFT_ALT_IMAGE_SUBTITLE_X 55
#define DISPLAY_TFT_ALT_IMAGE_SUBTITLE_Y 130

// message location
#define DISPLAY_TFT_MSG_X 5
#define DISPLAY_TFT_MSG_Y 65
#define DISPLAY_TFT_MSG_WIDTH 230
#define DISPLAY_TFT_MSG_AREA_HEIGHT 216
#define DISPLAY_TFT_MSG_HEIGHT 40
#define DISPLAY_TFT_MSG_TITLE_HEIGHT 16
#define DISPLAY_TFT_MSG_MAX_DISPLAY 4

// title/subtitle locations
#define DISPLAY_TFT_TITLE_X 5
#define DISPLAY_TFT_TITLE_Y 17
#define DISPLAY_TFT_TITLE_WIDTH 230
#define DISPLAY_TFT_TITLE_HEIGHT 22

#define DISPLAY_TFT_SUBTITLE_X 15
#define DISPLAY_TFT_SUBTITLE_Y 41
#define DISPLAY_TFT_SUBTITLE_WIDTH 190
#define DISPLAY_TFT_SUBTITLE_HEIGHT 17

#define DISPLAY_TFT_DASHBOARD_X 0
#define DISPLAY_TFT_DASHBOARD_Y 314
#define DISPLAY_TFT_DASHBOARD_HEIGHT 10
#define DISPLAY_TFT_DASHBOARD_WIDTH 240

// portrait
#define DISPLAY_TFT_KEYBOARD_X 5
#define DISPLAY_TFT_KEYBOARD_Y 195
#define DISPLAY_TFT_KEYBOARD_HEIGHT 120
#define DISPLAY_TFT_KEYBOARD_WIDTH 230

#define DISPLAY_TFT_MODAL_TITLE_X 5
#define DISPLAY_TFT_MODAL_TITLE_Y 22
#define DISPLAY_TFT_MODAL_TITLE_HEIGHT 25
#define DISPLAY_TFT_MODAL_SUBTITLE_X 5
#define DISPLAY_TFT_MODAL_SUBTITLE_Y 34
#define DISPLAY_TFT_MODAL_SUBTITLE_HEIGHT 12
#define DISPLAY_TFT_MODAL_INPUT_X 1
#define DISPLAY_TFT_MODAL_INPUT_Y 60
#define DISPLAY_TFT_MODAL_INPUT_HEIGHT 120
#define DISPLAY_TFT_MODAL_INPUT_WIDTH 270

#define DISPLAY_TFT_TICKER_X 231
#define DISPLAY_TFT_TICKER_Y 315
#define DISPLAY_TFT_TICKER_SIZE 3

#define DISPLAY_BUTTON_AREA_X 20
#define DISPLAY_BUTTON_AREA_Y 278
#define DISPLAY_BUTTON_HEIGHT 18
#define DISPLAY_BUTTON_WIDTH 60
#define DISPLAY_BUTTON_HORIZONTAL_OFFSET 75 // space between buttons

// landscape
#define DISPLAY_TFT_LS_KEYBOARD_X 5
#define DISPLAY_TFT_LS_KEYBOARD_Y 100
#define DISPLAY_TFT_LS_KEYBOARD_HEIGHT 140
#define DISPLAY_TFT_LS_KEYBOARD_WIDTH 312

#define DISPLAY_TFT_LS_MODAL_TITLE_X 5
#define DISPLAY_TFT_LS_MODAL_TITLE_Y 22
#define DISPLAY_TFT_LS_MODAL_TITLE_HEIGHT 25
#define DISPLAY_TFT_LS_MODAL_SUBTITLE_X 5
#define DISPLAY_TFT_LS_MODAL_SUBTITLE_Y 34
#define DISPLAY_TFT_LS_MODAL_SUBTITLE_HEIGHT 12
#define DISPLAY_TFT_LS_MODAL_INPUT_X 1
#define DISPLAY_TFT_LS_MODAL_INPUT_Y 60
#define DISPLAY_TFT_LS_MODAL_INPUT_HEIGHT 40
#define DISPLAY_TFT_LS_MODAL_INPUT_WIDTH 320

#define DISPLAY_TFT_HEIGHT 320
#define DISPLAY_TFT_WIDTH 240

#define DISPLAY_TFT_SPINNER_X 220
#define DISPLAY_TFT_SPINNER_Y 18
#define DISPLAY_TFT_SPINNER_RADIUS 15

#define DISPLAY_TFT_PROGRESS_BAR_X 50
#define DISPLAY_TFT_PROGRESS_BAR_Y 220
#define DISPLAY_TFT_PROGRESS_BAR_WIDTH 140
#define DISPLAY_TFT_PROGRESS_BAR_HEIGHT 20

#define DISPLAY_TFT_MAIN_SCROLL_UP_X 220
#define DISPLAY_TFT_MAIN_SCROLL_UP_Y 35
#define DISPLAY_TFT_MAIN_SCROLL_DOWN_X 220
#define DISPLAY_TFT_MAIN_SCROLL_DOWN_Y 260
#define DISPLAY_TFT_MAIN_SCROLL_RADIUS 6
#define DISPLAY_TFT_MAIN_SCROLL_TOUCH_RADIUS 20

#define DISPLAY_TFT_LOCK_BUTTON_X 1
#define DISPLAY_TFT_LOCK_BUTTON_Y 1
#define DISPLAY_TFT_LOCK_BUTTON_SIZE 20

#define DISPLAY_TFT_FLIP_BUTTON_X 219
#define DISPLAY_TFT_FLIP_BUTTON_Y 1
#define DISPLAY_TFT_FLIP_BUTTON_SIZE 20