#define TEXT_UPPER_VERTICAL_OFFSET_MULT 1
#define TEXT_LOWER_VERTICAL_OFFSET_MULT 9

//#define DISPLAY_TFT_SCREEN_LOCK_TIMEOUT 120000

#define DISPLAY_TFT_SPLASH_TITLE_X 85
#define DISPLAY_TFT_SPLASH_TITLE_Y 130

#define DISPLAY_TFT_SPLASH_SUBTITLE_X 45
#define DISPLAY_TFT_SPLASH_SUBTITLE_Y 200

#define DISPLAY_TFT_STATUS_X 10
#define DISPLAY_TFT_STATUS_Y 477
#define DISPLAY_TFT_STATUS_HEIGHT 25
#define DISPLAY_TFT_STATUS_WIDTH 150

#define DISPLAY_TFT_CACHE_STATUS_X 170
#define DISPLAY_TFT_CACHE_STATUS_Y 465
#define DISPLAY_TFT_CACHE_STATUS_HEIGHT 14
#define DISPLAY_TFT_CACHE_STATUS_WIDTH 100

#define DISPLAY_TFT_BATTERY_STATUS_X 276
#define DISPLAY_TFT_BATTERY_STATUS_Y 467
#define DISPLAY_TFT_BATTERY_STATUS_HEIGHT 10
#define DISPLAY_TFT_BATTERY_STATUS_WIDTH 20

#define DISPLAY_TFT_ALERT_X 50
#define DISPLAY_TFT_ALERT_Y 150
#define DISPLAY_TFT_ALERT_SUB_X 50
#define DISPLAY_TFT_ALERT_SUB_Y 220
#define DISPLAY_TFT_ALERT_HEIGHT 40

#define DISPLAY_TFT_LS_ALERT_X 10
#define DISPLAY_TFT_LS_ALERT_Y 150
#define DISPLAY_TFT_LS_ALERT_SUB_X 10
#define DISPLAY_TFT_LS_ALERT_SUB_Y 180
#define DISPLAY_TFT_LS_ALERT_HEIGHT 40

#define DISPLAY_TFT_MAIN_AREA_X 60
#define DISPLAY_TFT_MAIN_AREA_Y 145
#define DISPLAY_TFT_MAIN_AREA_HEIGHT 45

#define DISPLAY_TFT_MAIN_SUB_AREA_X 40
#define DISPLAY_TFT_MAIN_SUB_AREA_Y 190
#define DISPLAY_TFT_MAIN_SUB_AREA_HEIGHT 35

#define DISPLAY_TFT_MENU_X 25
#define DISPLAY_TFT_MENU_Y 122
#define DISPLAY_TFT_MENU_WIDTH 260
#define DISPLAY_TFT_MENU_HEIGHT 290
#define DISPLAY_TFT_MENU_LINE_HEIGHT 48 // was 40
#define DISPLAY_TFT_MENU_MAX_ITEM_LENGTH 12
#define DISPLAY_TFT_MENU_INDENT 10 // pixels to indent menu items
#define DISPLAY_TFT_MENU_VERTICAL_ITEM_OFFSET 20 // was 14
#define DISPLAY_TFT_MENU_VERTICAL_TEXT_OFFSET -12 // was -7

#define DISPLAY_TFT_MENU_TITLE_X 65
#define DISPLAY_TFT_MENU_TITLE_Y 122

#define DISPLAY_TFT_MENU_SCROLL_UP_X 300
#define DISPLAY_TFT_MENU_SCROLL_UP_Y 130
#define DISPLAY_TFT_MENU_SCROLL_DOWN_X 300
#define DISPLAY_TFT_MENU_SCROLL_DOWN_Y 370
#define DISPLAY_TFT_MENU_SCROLL_RADIUS 6
#define DISPLAY_TFT_MENU_SCROLL_TOUCH_RADIUS 20
#define DISPLAY_TFT_MAIN_IMAGE_X 35
#define DISPLAY_TFT_MAIN_IMAGE_Y 120
#define DISPLAY_TFT_MAIN_IMAGE_WIDTH 64
#define DISPLAY_TFT_MAIN_IMAGE_HEIGHT 48
#define DISPLAY_TFT_MAIN_IMAGE_SUBTITLE_X 55 // relative to bottom left corner of image
#define DISPLAY_TFT_MAIN_IMAGE_SUBTITLE_Y 130 // relative to bottom left corner of image

#define DISPLAY_TFT_ALT_IMAGE_X 35
#define DISPLAY_TFT_ALT_IMAGE_Y 120
#define DISPLAY_TFT_ALT_IMAGE_WIDTH 64
#define DISPLAY_TFT_ALT_IMAGE_HEIGHT 48
#define DISPLAY_TFT_ALT_IMAGE_SUBTITLE_X 55
#define DISPLAY_TFT_ALT_IMAGE_SUBTITLE_Y 130

// message location
#define DISPLAY_TFT_MSG_X 5
#define DISPLAY_TFT_MSG_Y 95
#define DISPLAY_TFT_MSG_WIDTH 310
#define DISPLAY_TFT_MSG_AREA_HEIGHT 350
#define DISPLAY_TFT_MSG_HEIGHT 50
#define DISPLAY_TFT_MSG_TITLE_HEIGHT 19
#define DISPLAY_TFT_MSG_MAX_DISPLAY 5
#define DISPLAY_TFT_MSG_TITLE_Y_OFFSET 16
#define DISPLAY_TFT_MSG_TITLE_X_OFFSET 20
#define DISPLAY_TFT_MSG_TS_X_OFFSET 85
#define DISPLAY_TFT_MSG_STATUS_X_OFFSET 5
#define DISPLAY_TFT_MSG_TITLE_ICON_Y_OFFSET 16
#define DISPLAY_STATUS_RADIUS 6

// title/subtitle locations
#define DISPLAY_TFT_TITLE_X 5
#define DISPLAY_TFT_TITLE_Y 23
#define DISPLAY_TFT_TITLE_WIDTH 310
#define DISPLAY_TFT_TITLE_HEIGHT 31

#define DISPLAY_TFT_SUBTITLE_X 15
#define DISPLAY_TFT_SUBTITLE_Y 49
#define DISPLAY_TFT_SUBTITLE_WIDTH 220
#define DISPLAY_TFT_SUBTITLE_HEIGHT 27

#define DISPLAY_TFT_DASHBOARD_X 0
#define DISPLAY_TFT_DASHBOARD_Y 445
#define DISPLAY_TFT_DASHBOARD_HEIGHT 18
#define DISPLAY_TFT_DASHBOARD_WIDTH 320

// portrait
#define DISPLAY_TFT_KEYBOARD_X 5
#define DISPLAY_TFT_KEYBOARD_Y 310
#define DISPLAY_TFT_KEYBOARD_HEIGHT 160
#define DISPLAY_TFT_KEYBOARD_WIDTH 310
#define DISPLAY_TFT_KEYBOARD_TEXT_VERT_OFFSET 16

#define DISPLAY_TFT_MODAL_TITLE_X 5
#define DISPLAY_TFT_MODAL_TITLE_Y 22
#define DISPLAY_TFT_MODAL_TITLE_HEIGHT 35
#define DISPLAY_TFT_MODAL_SUBTITLE_X 5
#define DISPLAY_TFT_MODAL_SUBTITLE_Y 54
#define DISPLAY_TFT_MODAL_SUBTITLE_HEIGHT 22
#define DISPLAY_TFT_MODAL_INPUT_X 1
#define DISPLAY_TFT_MODAL_INPUT_Y 80
#define DISPLAY_TFT_MODAL_INPUT_HEIGHT 140
#define DISPLAY_TFT_MODAL_INPUT_WIDTH 320

#define DISPLAY_TFT_TICKER_X 311
#define DISPLAY_TFT_TICKER_Y 471
#define DISPLAY_TFT_TICKER_SIZE 5

#define DISPLAY_BUTTON_AREA_X 5
#define DISPLAY_BUTTON_AREA_Y 415
#define DISPLAY_BUTTON_HEIGHT 25
#define DISPLAY_BUTTON_WIDTH 90
#define DISPLAY_BUTTON_PIXELS_PER_CHAR 5
#define DISPLAY_BUTTON_TEXT_VERT_ADJ 2
#define DISPLAY_BUTTON_HORIZONTAL_OFFSET 110 // space between buttons
#define DISPLAY_BUTTON_TEXT_SEND "Send"
#define DISPLAY_BUTTON_TEXT_MENU "Menu"
#define DISPLAY_BUTTON_TEXT_FILTER "Filter"

// landscape
#define DISPLAY_TFT_LS_KEYBOARD_X 5
#define DISPLAY_TFT_LS_KEYBOARD_Y 150
#define DISPLAY_TFT_LS_KEYBOARD_HEIGHT 170
#define DISPLAY_TFT_LS_KEYBOARD_WIDTH 312

#define DISPLAY_TFT_LS_MODAL_TITLE_X 5
#define DISPLAY_TFT_LS_MODAL_TITLE_Y 22
#define DISPLAY_TFT_LS_MODAL_TITLE_HEIGHT 25
#define DISPLAY_TFT_LS_MODAL_SUBTITLE_X 5
#define DISPLAY_TFT_LS_MODAL_SUBTITLE_Y 34
#define DISPLAY_TFT_LS_MODAL_SUBTITLE_HEIGHT 12
#define DISPLAY_TFT_LS_MODAL_INPUT_X 1
#define DISPLAY_TFT_LS_MODAL_INPUT_Y 60
#define DISPLAY_TFT_LS_MODAL_INPUT_HEIGHT 40
#define DISPLAY_TFT_LS_MODAL_INPUT_WIDTH 320

#define DISPLAY_TFT_HEIGHT 480
#define DISPLAY_TFT_WIDTH 320

#define DISPLAY_TFT_SPINNER_X 220
#define DISPLAY_TFT_SPINNER_Y 18
#define DISPLAY_TFT_SPINNER_RADIUS 15

#define DISPLAY_TFT_PROGRESS_BAR_X 50
#define DISPLAY_TFT_PROGRESS_BAR_Y 280
#define DISPLAY_TFT_PROGRESS_BAR_WIDTH 220
#define DISPLAY_TFT_PROGRESS_BAR_HEIGHT 30

#define DISPLAY_TFT_MAIN_SCROLL_UP_X 300
#define DISPLAY_TFT_MAIN_SCROLL_UP_Y 48
#define DISPLAY_TFT_MAIN_SCROLL_DOWN_X 300
#define DISPLAY_TFT_MAIN_SCROLL_DOWN_Y 390
#define DISPLAY_TFT_MAIN_SCROLL_RADIUS 6
#define DISPLAY_TFT_MAIN_SCROLL_TOUCH_RADIUS 20

#define DISPLAY_TFT_LOCK_BUTTON_X 1
#define DISPLAY_TFT_LOCK_BUTTON_Y 1
#define DISPLAY_TFT_LOCK_BUTTON_SIZE 30

#define DISPLAY_TFT_FLIP_BUTTON_X 289
#define DISPLAY_TFT_FLIP_BUTTON_Y 1
#define DISPLAY_TFT_FLIP_BUTTON_SIZE 30

// license/qr code
#define DISPLAY_TFT_LICENSE_INSTRUCTIONS_X 60
#define DISPLAY_TFT_LICENSE_INSTRUCTIONS_Y 380

#define DISPLAY_TFT_LICENSE_LINK_X 85
#define DISPLAY_TFT_LICENSE_LINK_Y 420

#define DISPLAY_TFT_LICENSE_DEVICE_X 55
#define DISPLAY_TFT_LICENSE_DEVICE_Y 450

#define DISPLAY_QR_VERSION 4
#define DISPLAY_QR_SCALE 7
